### ISSUE TITLE
Special characters not working on Terminal

### ISSUE THREAD

**Issue by miguelangelcv** [martrik/Haskelly#13]
When I try to enter a '[' or ']' to specify a list in the Terminal, it will not let me enter them (I hear the error sound). The special characters that don't work for me are those that are entered using 'Alt Gr' (I have a spanish keyboard)

**Comment by martrik** [comment]
Hola Miguel, gracias por ponerte en contacto con nosotros! I'm a bit confused now since you've changed the original issue. Does that mean that it's not present anymore? In any case, we will include a small fix that should address your initial problem. 

Regarding your second issue (Special characters), I'm not entirely sure what can be the problem. Just to clarify, you are using Windows right? Also, do you have any special terminal installed?

**Comment by miguelangelcv** [comment]
You can close the Issue, it's a Visual Studio Code bug :(

> https://github.com/Microsoft/vscode/issues/19440
