### ISSUE TITLE
Incorrect syntax highlighting?

### ISSUE THREAD

**Issue by kodaj** [martrik/Haskelly#6]
First of all: thanks a lot for writing Haskelly! I've only just started using it, and it's already helped me become a lot more productive. Keep it up, guys! The Haskell ecosystem is painfully lacking a simple and usable IDE - Haskelly might be the tool to fill this gap.

Regarding the potential bug: I've attached a screenshot of how the code below is syntax-colored in Haskelly - aren't all record fields supposed to look like the first one? I mean, shouldn't all record labels be colored yellow(ish) and their types be colored blue?

    -- A snapshot of the strategy's state at some point in time.
    data Strategy = Strategy {
        signalFinder :: SignalFinder
      , tradingState :: TradingState
      , position     :: Maybe Position
      , exitOrders   :: Maybe ExitOrders
      , tradeLog     :: TradeLog
      , pnl          :: PnL
    
![syntax_coloring](https://cloud.githubusercontent.com/assets/4332563/22177116/52b49622-e018-11e6-9dab-d8fa743205da.jpg)
} 

Environment info: I'm using version 0.3.0 of Haskelly on Windows 10.

**Comment by martrik** [comment]
@kodaj Thanks for your kind words, we really appreciate it. We've changed the Syntax Definition file that we were using to a new one (https://github.com/textmate/haskell.tmbundle) and the bug seems to be solved. The fix is available in the new version 0.3.1. Let us know if the bug has been solved. Thanks!

**Comment by kodaj** [comment]
@martrik  Thanks a lot for the quick reaction! It's looking much better now, but there's one thing I still don't quite understand: why is the first record label colored differently than the other labels? (Note that the `::` is also colored differently on the first line.)

![syntax_coloring](https://cloud.githubusercontent.com/assets/4332563/22177619/c71a9c60-e021-11e6-9c4f-11f57979402a.jpg)

**Comment by martrik** [comment]
I think this is due to the formatting that you are using to define the Type. To make the highlight be even you can either write the commas before the new line or start the first proper straight after the curly brace. For the Dark+ theme the former option seems to be the best.

Dark+:
![screen shot 2017-01-21 at 21 08 50](https://cloud.githubusercontent.com/assets/1800680/22177827/f11b0940-e01d-11e6-8ae0-18ace55e798a.png)

Monokai: 
![screen shot 2017-01-21 at 21 08 37](https://cloud.githubusercontent.com/assets/1800680/22177830/f5fb2544-e01d-11e6-9d92-2feb7dd81fd0.png)

**Comment by kodaj** [comment]
I see - thanks!
